### ISSUE TITLE
Tool does not work in old systems and Mac.

### ISSUE THREAD

**Issue by emalp** [0xPugal/SubDomz#25]
Various tools like:
- Anew
- Unfurl
are not installed by the install.sh script

The Output() function does not work on different versions of bash as the `cat/*` expects to cat all files which might not work everywhere (eg Mac)

The `mkdir -p ~/SubDomz/output/$domain/` command also expects bash to handle the expression run, however the $domain param is only set in the Main function. This does not work properly in Mac and $domain is empty during the dir creation.

I've got local changes ready to fix. More than happy to open a PR if permission is given.

**Comment by 0xPugazh** [comment]
I rewrite the code completely, hope the errors are fixed. Also, I don't know whether its runs on mac without any errors.
